/*
* FACTION LIST
*/

#define  FACTION_CIVILIAN 0
#define  FACTION_VIP 1
#define  FACTION_GROVE 2
#define  FACTION_BALLAS 3
#define  FACTION_VAGOS 4
#define  FACTION_AZTECAS 5
#define  FACTION_CRIPZ 6
#define  FACTION_TRIADS 7
#define  FACTION_RIFA 8
#define  FACTION_SOA 9
#define  FACTION_NANG 10
#define  FACTION_ITALIAN 11
#define  FACTION_BOUNTY 12
#define  FACTION_THUGLIFE 13
#define  FACTION_CREW 14
#define  FACTION_INTENSE_POLICE 15
#define  FACTION_SOLDIER 16
#define  FACTION_YAKUZA 17
#define  FACTION_SYNDICATE 18
#define  FACTION_BLOODMAFIA 19
#define  FACTION_MS13 20
#define  FACTION_BGMAFIA 21
#define  FACTION_343 22
